import Sidebar from '@/components/sidebar'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'

const geistSans = Poppins({ weight: '500', subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br">
      <body className={`${geistSans} antialiased`}>
        <Sidebar />
        {children}
      </body>
    </html>
  )
}
